[build]
  base    = "docs/website"
  command = "hugo --minify --baseURL \"$URL\""
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"

# Deploy Previews (Pull Requests)
[context.deploy-preview]
  command = "hugo --minify --baseURL \"$DEPLOY_PRIME_URL\""

# Branch Deploys
[context.branch-deploy]
  command = "hugo --minify --baseURL \"$DEPLOY_PRIME_URL\""
